/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsla.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mydsla.ui.internal.MydslaActivator;

public class MyDslAUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslaActivator.getInstance().getInjector("org.xtext.example.mydsla.MyDslA");
	}

}
