/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsla;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyDslAStandaloneSetup extends MyDslAStandaloneSetupGenerated {

	public static void doSetup() {
		new MyDslAStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
