/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsla;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslARuntimeModule extends AbstractMyDslARuntimeModule {
}
