/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsla.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyDslAUiModule extends AbstractMyDslAUiModule {

	public MyDslAUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
