/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydslb.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mydslb.ui.internal.MydslbActivator;

public class MyDslBUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslbActivator.getInstance().getInjector("org.xtext.example.mydslb.MyDslB");
	}

}
