/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydslb.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyDslBUiModule extends AbstractMyDslBUiModule {

	public MyDslBUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
