/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydslb;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyDslBStandaloneSetup extends MyDslBStandaloneSetupGenerated {

	public static void doSetup() {
		new MyDslBStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
