/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydslb.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydslb.parser.antlr.internal.InternalMyDslBParser;
import org.xtext.example.mydslb.services.MyDslBGrammarAccess;

public class MyDslBParser extends AbstractAntlrParser {

	@Inject
	private MyDslBGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyDslBParser createParser(XtextTokenStream stream) {
		return new InternalMyDslBParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MyDslBGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslBGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
