/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsla.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.mydsla.ui.internal.MydslaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslAExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MydslaActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MydslaActivator activator = MydslaActivator.getInstance();
		return activator != null ? activator.getInjector(MydslaActivator.ORG_XTEXT_EXAMPLE_MYDSLA_MYDSLA) : null;
	}

}
