/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsla.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsla.MyDslARuntimeModule;
import org.xtext.example.mydsla.MyDslAStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyDslAIdeSetup extends MyDslAStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyDslARuntimeModule(), new MyDslAIdeModule()));
	}
	
}
