/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsla.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslAScopeProvider extends DelegatingScopeProvider {
}
