/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydslb.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslBScopeProvider extends DelegatingScopeProvider {
}
