/*
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydslb.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydslb.MyDslBRuntimeModule;
import org.xtext.example.mydslb.MyDslBStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyDslBIdeSetup extends MyDslBStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyDslBRuntimeModule(), new MyDslBIdeModule()));
	}
	
}
